### ISSUE TITLE
Party tablist breaking on creation.

### ISSUE THREAD

**Issue by fyrmftw** [AlessioDP/Parties#14] opened 2018-01-31 17:08 UTC
**Logs:** https://pastebin.com/Y9A09bgF

**How to repeat the issue:**  
1. /party create Name
2. Tablist colour changes & changes priority of the tablist groups and moves it to the top.
3. Leave the server & rejoin
4. Tablist colour goes back to normal & priority of the groups.

**Config:** https://pastebin.com/S3Tegmp0

**Comment by AlessioDP** [comment] 2018-01-31 18:02
Thank you for the report, so the problem is only when you create a party and if you quit and re-enter it will be fixed?

**Comment by AlessioDP** [comment] 2018-01-31 18:47
Unfortunately, SortedTabList is not well developed and it can make some problems.

I changed the tag system with Parties 2.2 so, just wait for the next release ;)

**Closed by AlessioDP** 2018-01-31 18:47 UTC
