### ISSUE TITLE
An exception when using plugin Mypet and Parties

### ISSUE THREAD

**Issue by Sgwa** [AlessioDP/Parties#5] opened 2017-05-01 01:22 UTC
### Just an exception that rises when a player's pet (from [Mypet](https://www.spigotmc.org/resources/mypet.12725/) plugin on spigot) that is on a party kills a mob:

`[22:10:34 ERROR]: Could not pass event EntityDeathEvent to Parties v1.7.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.EntityZombie.die(EntityZombie.java:429) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.EntityPigZombie.damageEntity(SourceFile:148) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.attack(EntityMyPet.java:342) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:115) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1007) [MyPet-Premium-2.3.4.jar:?]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.n(EntityMyPet.java:939) [MyPet-Premium-2.3.4.jar:?]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.A_(EntityMyPet.java:1160) [MyPet-Premium-2.3.4.jar:?]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-54ec0b8-7b044de]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
        at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot.jar:git-Spigot-54ec0b8-7b044de]
        at org.bukkit.Location.distance(Location.java:439) ~[spigot.jar:git-Spigot-54ec0b8-7b044de]
        at com.alessiodp.parties.PlayerListener.onEntityDie(PlayerListener.java:450) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor526.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-54ec0b8-7b044de]
        ... 27 more
`

**Comment by AlessioDP** [comment] 2017-05-01 09:17
Fixed with 1.7.6 :)

The problem is that my plugin is trying to get the distance between 2 players but they are in a different world.

**Closed** 2017-05-01 09:28 UTC
